package mimetype

const (
	ApplicationGraphQL         = "application/graphql"
	ApplicationJavaScript      = "application/javascript"
	ApplicationJson            = "application/json"
	ApplicationJsonUtf8        = "application/json;charset=UTF-8"
	ApplicationAtomXml         = "application/atom+xml"
	ApplicationXml             = "application/xml"
	ApplicationXHtmlXml        = "application/xhtml+xml"
	ApplicationRssXml          = "application/rss+xml"
	ApplicationFormUrlencoded  = "application/x-www-form-urlencoded"
	ApplicationOctetStream     = "application/octet-stream"
	ApplicationProblemJson     = "application/problem+json"
	ApplicationProblemJsonUtf8 = "application/problem+json;charset=UTF-8"
	ApplicationProblemXml      = "application/problem+xml"
	ApplicationStreamJson      = "application/stream+json"
	ApplicationLDJson          = "application/ld+json"
	ApplicationMSWord          = "application/msword"
	ApplicationPdf             = "application/pdf"
	ApplicationSql             = "application/sql"
	ApplicationVndApiJson      = "application/vnd.api+json"
	ApplicationVndMsExcel      = "application/vnd.ms-excel"
	ApplicationVndMsPowerPoint = "application/vnd.ms-powerpoint"
	ApplicationVndOAsisODText  = "application/vnd.oasis.opendocument.text"
	ApplicationZip             = "application/zip"
	ApplicationZStd            = "application/zstd"

	MultipartFormData = "multipart/form-data"
	MultipartMixed    = "multipart/mixed"
	MultipartRelated  = "multipart/related"

	AudioMpeg = "audio/mpeg"
	AudioOgg  = "audio/ogg"

	ImageGif  = "image/gif"
	ImageJpeg = "image/jpeg"
	ImagePng  = "image/png"

	TextEventStream = "text/event-stream"
	TextCss         = "text/css"
	TextCsv         = "text/csv"
	TextHtml        = "text/html"
	TextPhp         = "text/php"
	TextPlain       = "text/plain"
	TextXml         = "text/xml"
	TextMarkdown    = "text/markdown"
)
